### PR TITLE
fix: parity with js changes

### PR DESCRIPTION
**Pull request by aniketbiprojit**

### CODE REVIEW

**Review by seveibar — APPROVED** [review]

**Comment by seveibar** [comment]
Cc @codetheweb not sure if those comments were purposeful

**Comment by seveibar** [comment]
Maybe it was to give a link to inspect?

**Comment by seveibar** [comment]
Lets wait for the codetheweb prior to merge @aniketbiprojit

**Comment by aniketbiprojit** [comment]
Yeah. I also thought they gave the link but I feel the details options feels much more cleaner especially if we push on open PRs.

**Review by andrii-balitskyi — APPROVED** [review]

**Comment by razor-x** [comment]
Yes! Thank you, the comments are redundant with the checks integration.

**Review by codetheweb — APPROVED** [review]
lgtm

**Pull request merged**
